-- Durable state for the multi-user server.  IDs are generated by the
-- repository so this migration does not require an extension for UUIDs.
CREATE TABLE IF NOT EXISTS qp_server_sessions (
    id uuid PRIMARY KEY,
    user_id text NOT NULL,
    channel_id text NOT NULL,
    external_id text NOT NULL,
    state jsonb NOT NULL DEFAULT '{}'::jsonb,
    -- Monotonic per-session fencing generation; every claimed run gets the
    -- next value so a reused sandbox cannot accept an older execution.
    epoch bigint NOT NULL DEFAULT 0,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, channel_id, external_id)
);

ALTER TABLE qp_server_sessions
    ADD COLUMN IF NOT EXISTS epoch bigint NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS qp_server_sessions_user_updated_idx
    ON qp_server_sessions (user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS qp_server_definitions (
    version text PRIMARY KEY,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS qp_server_runs (
    id uuid PRIMARY KEY,
    session_id uuid NOT NULL REFERENCES qp_server_sessions(id),
    user_id text NOT NULL,
    channel_id text NOT NULL,
    request_id text NOT NULL,
    "input" jsonb NOT NULL,
    definition_version text NOT NULL,
    status text NOT NULL DEFAULT 'queued',
    epoch bigint NOT NULL DEFAULT 0,
    worker_id text,
    cancel_requested boolean NOT NULL DEFAULT FALSE,
    lease_until timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at timestamptz,
    finished_at timestamptz,
    UNIQUE (user_id, request_id)
);

CREATE INDEX IF NOT EXISTS qp_server_runs_queue_idx
    ON qp_server_runs (status, created_at, id);
CREATE INDEX IF NOT EXISTS qp_server_runs_user_status_idx
    ON qp_server_runs (user_id, status);
CREATE INDEX IF NOT EXISTS qp_server_runs_lease_idx
    ON qp_server_runs (status, lease_until);
CREATE INDEX IF NOT EXISTS qp_server_runs_session_idx
    ON qp_server_runs (session_id, created_at, id);

CREATE TABLE IF NOT EXISTS qp_server_events (
    run_id uuid NOT NULL REFERENCES qp_server_runs(id) ON DELETE CASCADE,
    seq bigint NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (run_id, seq)
);

CREATE TABLE IF NOT EXISTS qp_server_messages (
    id uuid PRIMARY KEY,
    session_id uuid NOT NULL REFERENCES qp_server_sessions(id) ON DELETE CASCADE,
    run_id uuid NOT NULL REFERENCES qp_server_runs(id) ON DELETE CASCADE,
    user_id text NOT NULL,
    seq bigint NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (session_id, seq)
);

CREATE INDEX IF NOT EXISTS qp_server_messages_session_idx
    ON qp_server_messages (session_id, seq);

CREATE TABLE IF NOT EXISTS qp_server_tool_calls (
    run_id uuid NOT NULL REFERENCES qp_server_runs(id) ON DELETE CASCADE,
    call_id text NOT NULL,
    name text NOT NULL,
    arguments jsonb NOT NULL,
    status text NOT NULL DEFAULT 'running',
    result jsonb,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (run_id, call_id)
);

CREATE TABLE IF NOT EXISTS qp_server_approvals (
    id uuid PRIMARY KEY,
    run_id uuid NOT NULL REFERENCES qp_server_runs(id) ON DELETE CASCADE,
    user_id text NOT NULL,
    call_id text NOT NULL,
    status text NOT NULL DEFAULT 'pending',
    expires_at timestamptz NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    decided_at timestamptz,
    UNIQUE (run_id, call_id)
);

CREATE INDEX IF NOT EXISTS qp_server_approvals_user_idx
    ON qp_server_approvals (user_id, status, expires_at);

CREATE TABLE IF NOT EXISTS qp_server_files (
    id uuid PRIMARY KEY,
    user_id text NOT NULL,
    file_id text NOT NULL,
    name text NOT NULL,
    object_key text NOT NULL,
    size_bytes bigint NOT NULL CHECK (size_bytes >= 0),
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, file_id)
);

CREATE INDEX IF NOT EXISTS qp_server_files_user_idx
    ON qp_server_files (user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS qp_server_memories (
    id uuid PRIMARY KEY,
    user_id text NOT NULL,
    session_id uuid REFERENCES qp_server_sessions(id) ON DELETE SET NULL,
    text text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS qp_server_memories_user_idx
    ON qp_server_memories (user_id, created_at DESC);
